apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-production
# Seems to cause potential issues
# namePrefix: prod-
resources:
- resources/sealed_secret_postgres_production.yaml
- resources/route_frontend_prod.yaml
- resources/route_backend_prod.yaml
- ./../../base
patches:
- path: patches/persistentvolumeclaim_todoapp_prod.yaml
- path: patches/configmap_todoapp_prod.yaml
images:
- digest: sha256:ab22f5a171be228d4f358576475ef7ccaf1597658bfb487961dcd40173f543b2
  name: PROJECT/BACKENDIMAGE
  newName: hinichijou/todo_app_backend-production
  newTag: "4.9"
- digest: sha256:8740f14c7b299a319733a72f94ada99e680574d4717850dcb6ddfed6a6e465a0
  name: PROJECT/BROADCASTERIMAGE
  newName: hinichijou/broadcaster-production
  newTag: "4.9"
- digest: sha256:8c0457fe1af8a70bf7d66ea71911f47f1de9ccf3dbf00467d7b8a0af87b33779
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-production
  newTag: "4.9"
- digest: sha256:73670690b28fc7bab4f26561931e0e4cd9f9db66876235549727a1e4f1bfba25
  name: PROJECT/FRONTENDIMAGE
  newName: hinichijou/todo_app_frontend-production
  newTag: "4.9"
- digest: sha256:fc5d150a7706130ee0767cd8527e95f8d7909587dc608328776d0d4aa7e3ebdd
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: hinichijou/wikipedia_todo_job-production
  newTag: "4.9"
