apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
  - name: PROJECT/FRONTENDIMAGE
    newName: hinichijou/todo_app_frontend:19oavfbl
  - name: PROJECT/BACKENDIMAGE
    newName: hinichijou/todo_app_backend:aknp6vo7
  - name: PROJECT/WIKIPEDIATODOJOBIMAGE
    newName: hinichijou/wikipedia_todo_job:gtioyq7v
configMapGenerator:
- name: db-init
  files:
  - manifests/init_todo_db.sql
resources:
  - manifests/gateway.yaml
  - manifests/configmap_todoapp.yaml
  - manifests/deployment_todoapp.yaml
  - manifests/route_frontend.yaml
  - manifests/route_backend.yaml
  - manifests/service_todoapp.yaml
  - manifests/service_postgres.yaml
  - manifests/statefulset_postgres.yaml
  - manifests/secret_postgres.yaml
  - manifests/configmap_postgres.yaml
  - manifests/wikipedia_todo_job.yml
  - manifests/healthcheckpolicies.yaml