---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBHB71m8mSa88lwjKDNtbV1yHXefGYIDNirPmroPERtvwTnLhmnkhVfeiofN55ExNxa8KHUDDbsonUN74U9kZanr2KoAI3zStiZcrTuddL+/3ZAYtyf/0R4Nbg7reZcIUHaBsuUD3ac06bzifSsYtqSCYf4khDKEPGa4dV3I+Uwje+nwXfu6NCFjaNPX7kBL0KysPZswyGO0/lLGlsQolQV1TFtdo/vfmKWmFtGX86YcSjmUkWNXqk0BBy1LhMbmZd3tJS2uzbZUXELPABIXXZdX3sWR0JH4rkpIh3Zi785QseyTSAvQSdiMSqYZd/UVFye/4xpISACF6SmveEkGwhTek6BWVUWY9Jj+hcnHYGV8+2WgyRVo4yR2kVuRvpJk9hylr8EFOGwukPmgoxe9HaIGrXaF/SaG7CY7XC/pRW/niCUP36+HoNPSI3pyo/9o4a/2QxV0nY5l/d8jcda32CZABRArs9kslgIX7v1KIz0in0FJtNlWcjD5KA8Ixs2b46elnMmoC0w8CgX2Yflsgqwv0WnidnVQrZGk4/W+AqZ2tWfw9n8Awn034DyMY4KTc1kwZtlCwxF9bZrbEt9GEt1d0MPhn68DehuUKnYhXqOEvSLIIKZTdGA2D4T0NpLTRMudQrEcBNVZkJCuHsU5PTgpMgpHsaLFg8Bu4AyBetP4IjOEwPoJS+Nj5Z64lE38VBGGo966ZLy6jvXlXc=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-staging
