apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: project-production
  name: todo-backend-route
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /todoapp-prod/api