---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAjCoClVjV8vOb5g0rn1V7P0Lk51EyVfVi8oIpqeuOBukwC5jcU/EuB52Vf3tN/T7fIZeC8ICg7TFkN9ishJBUupVfY9dbSvXdO0/Oo6zhN+fhxaUOLAtqQb78GTSJjWySApCk4DTRfcTWCN4FTuFB2YdY1YUy+JFxu0/7gWnj+7Y5egHhirSlEbZy6+IUeRpe/Ox40rNOQn3XeGkBccS8Acx36qgAhQ042hxuHc+h9diGREiZuHH3IZjnQi2apzzV+w3vSNaQvADbYZzvlg7TYZWBg1gGpZGjdCOyB7Zll1AAhNvlN/WS7OT+uQTqRbB5d/d1Bw2s+OEo75EwbXMfFcLqTAP4TiRVQYgihVRpMLBnw2AnZo6LLr7egC3ISxu4CtXq5+8q468D+vRn1zwyc78OydHp2nrfEvWSE7nht6ZFXkOiytpou6pKxBFTSo2bvNYB6I7k1v/6gSWDeYRguXIZ/hjChWNPmOoRSL9flt2NSR+04wvlkFfFi3/nGFAo953AWr9TKSRFjqoYMEOCoQh0oO8pVDWfqMH0PcUCkTtHZNHg7FmuDN03+YJvpUDTpyjaHRs6wx1P5K4+CLiwAaL/vmzs0pBJ+zLX0ITRQLWpz4eb4Vq4PpVWOIxTqh0clDPl2QLXdcF1qRaQsT0El6zfR3Prw/1II4OOIfQ/dCq5ATpTOlCzdL0WfopdIZuAV5Z5PydFo0peihCQ=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-production
