apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: logoutput-writer
          image: hinichijou/log_output-writer:7xzfeyk3
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
        - name: logoutput-reader
          image: hinichijou/log_output-reader:3q8enxpj
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files