apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: log-output
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: logoutput-writer
          image: hinichijou/log_output-writer:7xzfeyk3
          volumeMounts: # Mount volume
          - name: log-output
            mountPath: /usr/src/app/files
        - name: logoutput-reader
          image: hinichijou/log_output-reader:itpcyjb0
          volumeMounts: # Mount volume
          - name: log-output
            mountPath: /usr/src/app/files
      securityContext:
        fsGroup: 1001