apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpongapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpongapp
  template:
    metadata:
      labels:
        app: pingpongapp
    spec:
      containers:
        - name: pingpong
          image: PROJECT/PINGPOGAPPIMAGE
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-postgres-config
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: postgres-config
      securityContext:
        fsGroup: 1001