name: 'Build Image'
description: 'Builds images and adds them to kustomization.yaml'
inputs:
  namespace:
    required: true
  image_name:
    required: true
  app_folder:
    required: true
  build_folder:
    required: true
  image_alias:
    required: true
  build_arg_string:
    required: false
outputs:
  built:
    value: "${{ steps.build.outputs.built }}"

runs:
  using: "composite"
  steps:
    - name: Build & push
      id: 'build'
      working-directory: "${{ inputs.app_folder }}"
      shell: bash
      # awk: print the third field delimited by space from the line containing digest
      run: |
        IMAGE_TAG="${{ inputs.namespace }}/${{ inputs.image_name }}"
        docker build ${{ inputs.build_arg_string }} --tag $IMAGE_TAG "${{ inputs.build_folder }}"
        SHA="$(docker push $IMAGE_TAG | awk '/digest:/ { print $3 }')"
        echo "built=${{ inputs.image_alias }}=$IMAGE_TAG@$SHA" >> $GITHUB_OUTPUT