apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: project
spec:
  #3.10: should be daily. Now once per minute for testing
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # 3.10: Based on https://docs.cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
          serviceAccountName: db-backup-sa
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: backup
            image: PROJECT/DBBACKUPJOBIMAGE
            env:
              - name: POSTGRES_SVC
                value: postgres-svc
              - name: POSTGRES_PORT
                value: "5432"
              - name: BUCKET_URL
                value: https://storage.googleapis.com/upload/storage/v1/b/project-db-backup-bucket/o
              - name: METADATA_URL
                value: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
              - name: BACKUP_PATH
                value: /usr/src/app
              - name: BACKUP_FILE
                value: backup.sql
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: PGUSER
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: PGDATABASE
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: secret-postgres-config
                    key: POSTGRES_PASSWORD
          restartPolicy: OnFailure