apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes: # Define volume
        - name: todoapp
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp-frontend
          image: PROJECT/FRONTENDIMAGE
          volumeMounts: # Mount volume
            - name: todoapp
              mountPath: /app/dynamic/images
          envFrom:
            - configMapRef:
                name: todoappfrontend-config
            - configMapRef:
                name: todoappapiroutes-config
        - name: todoapp-backend
          image: PROJECT/BACKENDIMAGE
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-postgres-config
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: todoappbackend-config
            - configMapRef:
                name: postgres-config
      securityContext:
        fsGroup: 1001
  strategy:
    type: Recreate