apiVersion: v1
kind: Secret
metadata:
    name: secret-postgres-config
    namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0shXalX6jcsOwXF3rtx5JQ==,iv:oJHXQT/3dXKgVVXQU/wx+1V70VPCpTueBEBzJvn5VJw=,tag:KQrnQwxnZt+MI7sMGhsoVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOXRGdUFxRWExZmZmN0g5
            b1pUdkIyUisxWTVCZXBkZUZkYzNJd3JWSmdJCmU0dVcwRzhOU1pSN2hQNzRqZGxi
            ZmFPVmNGYWlkbFBzd0dsbEg0S2dKVUUKLS0tIHlRcVhPZWdpTTZwVVBQdmcxYzJT
            alVpRGhFUWdpT1ViNysxSjkwVVpOU3MKjnJzm1CKhSCLq7VyFLKBj9NPnG5NTPza
            WrMQoMjdhSg99ACygpsFP8qzcVMIq4AjP8q53cAhb5uLzNidhvCRgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5gjhdh98xnct8qy70y5ga2dr2veqmlnq2h2w5r6f3u4gtd299rqjt4yss
    encrypted_regex: ^(data)$
    lastmodified: "2026-08-03T17:20:22Z"
    mac: ENC[AES256_GCM,data:+x6BxWThiFax8qIEok0epYscHWqYEw6j/ttyXhIWHrbg3jbBvSzbxJxuHDcIfiHaG1YNRxLf4en8E9OzXCjU0ZOBZU1HKBW+ig+sTLig/G4JgjIeePc71JXOvnaUR7OscqA8VH2IBjqHiGdiGGjAnUTZe0A/RZwh8zlpS2RV5C4=,iv:ijir4GYEBYIeixDtDGx0Kf3Wqd10za4YPKwfNxxRrN8=,tag:Jdk5wv/QRqAQ+747Es0Eew==,type:str]
    version: 3.13.3
