apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
configMapGenerator:
- name: db-init
  files:
  - ./init_todo_db.sql
resources:
  - configmap_todoapp.yaml
  - deployment_todoapp.yaml
  - ingress.yaml
  - service_todoapp.yaml
  - service_postgres.yaml
  - statefulset_postgres.yaml
  - secret_postgres.yaml
  - configmap_postgres.yaml
  - wikipedia_todo_job.yml