apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
configMapGenerator:
- name: todos-data
  files:
  - ./todos.json
resources:
  - configmap_todoapp.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml