# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: access-backend
# spec:
#   podSelector:
#     matchLabels:
#       app: todoapp-backend
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels:
#           app: todoapp-frontend