---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBijES9TycKMhMJ3G1F/8MhkFbKkaU+J1QLpe6nB0zuxoxRu3mkO7shFsg3cjS04Ha8EOWN213D5LaHMkQRWHNerVnH5rNB0rWDcAGfR+Ae/S2YCZSKaKjHPJLXZNnBN2cK5dhe1I+BVdGa8d4JzsdcC9mZ+mYdTTa4HLR028FzraaNZuQG5pe0fvBK1HsRQIeGs2frBfHU551HZR6/HGbYxrHDLFraQjQv4gOQkQU8L3mRIZm8MRI1umSqR7+i3gPGHDDAvKt+zSaKIdedBvmuJUcoQlK+5hLVoyGoq7wpg73GbSERdqSqR2XMtfMB+15npXjgi6xNclNtG+OwJOG9kvWkxRU6BiDGMdE6emcniClJhcLsq0O+N+7mkN2H1HJ/LyjQIP5gULdsm3GzKCb/3mmARvosaycXuGoH5garRT4eO5Yeyw8TKQ5eguj6cFHtgEWGljBrFfvTSY5hE+EwK2YAxorkSteHyJ0YUc18jth1HJxQVMg2B9qY3+XTPNkbsDOnAhNyCYUR8bcgtPtyoDl0VvHmCma+G0KIAaZQ+9yibyzDcQI0CP7uW6NvmNhSr/nTxY+TwwGUPkPXP7wAOZxRd62miwoh7edn7ju6yNl8aSrZENZxguZntHUh2QBTw5F6PcZSuCMVVvT2J3UdiLHdasAQfMKJrkV1E5isGvhRgjY+BRjksjbVDKzXG0siUM/OgpkYUd+4Tw4=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project
