apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
- resources/sealed_secret_postgres_staging.yaml
- resources/route_frontend_staging.yaml
- resources/route_backend_staging.yaml
- ./../../base
patches:
- path: patches/db_backup_job_staging.yaml
- path: patches/persistentvolumeclaim_todoapp_staging.yaml
- path: patches/configmap_todoapp_staging.yaml
images:
- digest: sha256:b5a35754d57eda995326fb508f9630a830e0a45c1e34e4898176ff1c88129254
  name: PROJECT/BACKENDIMAGE
  newName: hinichijou/todo_app_backend-staging
- digest: sha256:c6d8ece4b4ae90957b04eb2f4fb098e4f5d8841b599057317da958c70715d59a
  name: PROJECT/BROADCASTERIMAGE
  newName: hinichijou/broadcaster-staging
- digest: sha256:8302161185615bcb98be2385cb82c4cc8a9e159045e332443361bcf972a89e63
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-staging
- digest: sha256:081482efb1cef2bd0de0b0f84975bd40259f2c0491b84ad7ba65e074569c0ec5
  name: PROJECT/FRONTENDIMAGE
  newName: hinichijou/todo_app_frontend-staging
  newTag: d1b883b203b9007788edb1a800248d0d072ea166
- digest: sha256:a928777459f87c2998e01929a84a63fcd5c49189a7bf38c01f64b72988934882
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: hinichijou/wikipedia_todo_job-staging
