apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
- resources/sealed_secret_postgres_staging.yaml
- resources/route_frontend_staging.yaml
- resources/route_backend_staging.yaml
- ./../../base
patches:
- path: patches/db_backup_job.yaml
- path: patches/persistentvolumeclaim_todoapp_staging.yaml
- path: patches/configmap_todoapp_staging.yaml
images:
- name: PROJECT/BACKENDIMAGE
  newName: sha256
  newTag: 881e88500295138f883a0cd44a9b842af746a319a49c237d0bcc34760dff5b83
- name: PROJECT/BROADCASTERIMAGE
  newName: sha256
  newTag: 52763d12dd0f1a3e0c3c59ad99267dc838231395799b7e78e784d9ed4f30fc1b
- name: PROJECT/DBBACKUPJOBIMAGE
  newName: sha256
  newTag: 97931842ed4a50f8ecaf784e63e96dfda3f0e432e6dc7fcf20b72371d9086621
- name: PROJECT/FRONTENDIMAGE
  newName: sha256
  newTag: e39bcf688cd204ce43fb9e0974a2a1df6b9f6886801f972506721839c1b834ec
- name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: sha256
  newTag: ff4753077864f9d71945da6b2141df9866aaa0e01d708f28e26f171e0cb94587
