apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
  - manifests/sealed_secret_postgres_staging.yaml
  - ./../../base
patches:
  - path: manifests/db_backup_job.yaml