name: Release application

on:
  push:
  workflow_dispatch:
    inputs:
      deploy_build_all:
        description: Build and Deploy the whole application.
        required: true
        type: boolean
        default: false
      deploy_build_necessary:
        description: Deploy application, build images only if necessary.
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: "${{ secrets.GKE_PROJECT }}"
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  FRONTEND_IMAGE_NAME: frontend
  FRONTEND_IMAGE_ALIAS: PROJECT/FRONTENDIMAGE
  FRONTEND_FOLDER: ./todo_app_frontend
  BACKEND_IMAGE_NAME: backend
  BACKEND_IMAGE_ALIAS: PROJECT/BACKENDIMAGE
  BACKEND_FOLDER: ./backend
  WIKIPEDIA_JOB_IMAGE_NAME: wikipedia_job
  WIKIPEDIA_JOB_IMAGE_ALIAS: PROJECT/WIKIPEDIATODOJOBIMAGE
  WIKIPEDIA_JOB_FOLDER: ./wikipedia_todo_job
  TODOAPP_DEPLOYMENT: todoapp-dep
  MAIN_NAMESPACE: project

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: GKE_PROJECT
    defaults:
      run:
        working-directory: ./todo_app

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            manifests:
              - 'todo_app/manifests/**'
              - 'todo_app/kustomization.yaml'
            frontend:
              - 'todo_app/todo_app_frontend/**'
            backend:
              - 'todo_app/backend/**'
            wikipedia_todo_job:
              - 'todo_app/wikipedia_todo_job/**'

      - name: 'Have deploy relevant files changed'
        id: 'file_changes'
        run: |
          echo "deploy=${{
              steps.changes.outputs.frontend == 'true' ||
              steps.changes.outputs.backend == 'true' ||
              steps.changes.outputs.wikipedia_todo_job == 'true' ||
              steps.changes.outputs.manifests == 'true' ||
              inputs.deploy_build_all ||
              inputs.deploy_build_necessary
            }}" >> $GITHUB_OUTPUT

      - if: steps.file_changes.outputs.deploy == 'true'
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: 'Set up Cloud SDK'
        if: steps.file_changes.outputs.deploy == 'true'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Use gcloud CLI'
        if: steps.file_changes.outputs.deploy == 'true'
        run: gcloud info

      - if: steps.file_changes.outputs.deploy == 'true'
        run: gcloud --quiet auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        if: steps.file_changes.outputs.deploy == 'true'
        uses: 'google-github-actions/get-gke-credentials@v3'
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Set up Kustomize
        if: steps.file_changes.outputs.deploy == 'true'
        uses: imranismail/setup-kustomize@v3

      - name : 'Build & Publish frontend image'
        if: steps.changes.outputs.frontend == 'true' || inputs.deploy_build_all
        uses: ./.github/actions/build_image.yaml
        with:
          image_name: "${{ env.FRONTEND_IMAGE_NAME }}"
          build_folder: "${{ env.FRONTEND_FOLDER }}"
          image_alias: ${{ env.FRONTEND_IMAGE_ALIAS }}

      - name : 'Fetch existing frontend image (builds the image if existing image for the current branch not found)'
        if: steps.changes.outputs.frontend == 'false' && steps.file_changes.outputs.deploy == 'true'  && !inputs.deploy_build_all
        uses: ./.github/actions/fetch_image.yaml
        with:
          image_name: "${{ env.FRONTEND_IMAGE_NAME }}"
          build_folder: "${{ env.FRONTEND_FOLDER }}"
          image_alias: ${{ env.FRONTEND_IMAGE_ALIAS }}

      - name : 'Build & Publish backend image'
        if: steps.changes.outputs.backend == 'true' || inputs.deploy_build_all
        uses: ./.github/actions/build_image.yaml
        with:
          image_name: "${{ env.BACKEND_IMAGE_NAME }}"
          build_folder: "${{ env.BACKEND_FOLDER }}"
          image_alias: ${{ env.BACKEND_IMAGE_ALIAS }}

      - name : 'Fetch existing backend image (builds the image if existing image for the current branch not found)'
        if: steps.changes.outputs.backend == 'false'  && steps.file_changes.outputs.deploy == 'true' && !inputs.deploy_build_all
        uses: ./.github/actions/fetch_image.yaml
        with:
          image_name: "${{ env.BACKEND_IMAGE_NAME }}"
          build_folder: "${{ env.BACKEND_FOLDER }}"
          image_alias: ${{ env.BACKEND_IMAGE_ALIAS }}

      - name : 'Build & Publish wikipedia todo job image'
        if: steps.changes.outputs.wikipedia_todo_job == 'true' || inputs.deploy_build_all
        uses: ./.github/actions/build_image.yaml
        with:
          image_name: "${{ env.WIKIPEDIA_JOB_IMAGE_NAME }}"
          build_folder: "${{ env.WIKIPEDIA_JOB_FOLDER }}"
          image_alias: ${{ env.WIKIPEDIA_JOB_IMAGE_ALIAS }}

      - name : 'Fetch existing wikipedia todo job image (builds the image if existing image for the current branch not found)'
        if: steps.changes.outputs.wikipedia_todo_job == 'false'  && steps.file_changes.outputs.deploy == 'true' && !inputs.deploy_build_all
        uses: ./.github/actions/fetch_image.yaml
        with:
          image_name: "${{ env.WIKIPEDIA_JOB_IMAGE_NAME }}"
          build_folder: "${{ env.WIKIPEDIA_JOB_FOLDER }}"
          image_alias: ${{ env.WIKIPEDIA_JOB_IMAGE_ALIAS }}

      - name: 'Install SOPS'
        if: steps.file_changes.outputs.deploy == 'true'
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.13.3/sops-v3.13.3.linux.amd64
          sudo mv sops-v3.13.3.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

      # Reason for the set/create step split: GITHUB_ENV variables only become available in the next step
      - name: 'Set name for namespace'
        if: steps.file_changes.outputs.deploy == 'true'
        #The kustomize.yaml namespace will override the namespace set to the resource yamls
        run: |-
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            echo "NAMESPACE=$MAIN_NAMESPACE" >> $GITHUB_ENV
          else
            echo "NAMESPACE=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi

      - name: 'Create namespace'
        if: steps.file_changes.outputs.deploy == 'true'
        #The kustomize.yaml namespace will override the namespace set to the resource yamls
        run: |-
          kubectl create namespace "$NAMESPACE" || true
          kubectl config set-context --current --namespace="$NAMESPACE"
          kustomize edit set namespace "$NAMESPACE"

      - name: Deploy
        if: steps.file_changes.outputs.deploy == 'true'
        env:
          SOPS_AGE_KEY: "${{ secrets.SOPS_AGE_KEY }}"
        # Since the secret is applied separately it needs to be set the namespace separately
        run: |-
          sops --decrypt manifests/enc_secret_postgres.yaml | kubectl apply -n $NAMESPACE -f -
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $TODOAPP_DEPLOYMENT
          kubectl get services -o wide