apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
images:
- name: PROJECT/LOGOUTPUTREADERIMAGE
  newName: hinichijou/log_output-reader
  newTag: main-25f39af2cf78004af8d4c2ca7b72eafd95abd9ba
- name: PROJECT/LOGOUTPUTWRITERIMAGE
  newName: hinichijou/log_output-writer
  newTag: main-25f39af2cf78004af8d4c2ca7b72eafd95abd9ba
- name: PROJECT/PINGPONGAPPIMAGE
  newName: hinichijou/pingpong_application
  newTag: main-25f39af2cf78004af8d4c2ca7b72eafd95abd9ba
configMapGenerator:
- files:
  - assets/information.txt
  name: information-txt-config
resources:
- manifests/analysistemplate_cpu_usage.yaml
- manifests/persistentvolumeclaim_log_output.yaml
- manifests/configmap_log_output.yaml
- manifests/deployment_log_output.yaml
- manifests/service_log_output_reader.yaml
- manifests/route_log_output.yaml
- manifests/rollout_ping_pong.yaml
- manifests/deployment_ping_pong.yaml
- manifests/service_ping_pong.yaml
- manifests/route_ping_pong.yaml
- manifests/service_postgres.yaml
- manifests/statefulset_postgres.yaml
- manifests/sealed_secret_postgres.yaml
- manifests/configmap_postgres.yaml
