apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
images:
  - name: PROJECT/PINGPOGAPPIMAGE
    newName: hinichijou/pingpong_application:q8msboac
  - name: PROJECT/LOGOUTPUTREADERIMAGE
    newName: hinichijou/log_output-reader:jqznch4x
  - name: PROJECT/LOGOUTPUTWRITERIMAGE
    newName: hinichijou/log_output-writer:7xzfeyk3
configMapGenerator:
- name: information-txt-config
  files:
  - assets/information.txt
resources:
  - manifests/gateway.yaml
  - manifests/persistentvolumeclaim_log_output.yaml
  - manifests/configmap_log_output.yaml
  - manifests/deployment_log_output.yaml
  - manifests/service_log_output_reader.yaml
  - manifests/route_log_output.yaml
  - manifests/deployment_ping_pong.yaml
  - manifests/service_ping_pong.yaml
  - manifests/route_ping_pong.yaml
  - manifests/service_postgres.yaml
  - manifests/statefulset_postgres.yaml
  - manifests/secret_postgres.yaml
  - manifests/configmap_postgres.yaml