apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
images:
- digest: sha256:7d566db02856505712985c7ffec9002e36e5f529acd1969da67866d436139351
  name: PROJECT/LOGOUTPUTREADERIMAGE
  newName: hinichijou/log_output-reader
- digest: sha256:d30893ab19b745bebbb76a347d6fd2ad0e96b1dc944ca1c7a50307cb677fe7ab
  name: PROJECT/LOGOUTPUTWRITERIMAGE
  newName: hinichijou/log_output-writer
- digest: sha256:5c618b92266c7235194b1595fe4f6cf22d8fef38c1434a3563d87fefb29b718d
  name: PROJECT/PINGPONGAPPIMAGE
  newName: hinichijou/pingpong_application
configMapGenerator:
- files:
  - assets/information.txt
  name: information-txt-config
resources:
- manifests/analysistemplate_cpu_usage.yaml
- manifests/persistentvolumeclaim_log_output.yaml
- manifests/configmap_log_output.yaml
- manifests/deployment_log_output.yaml
- manifests/service_log_output_reader.yaml
- manifests/route_log_output.yaml
- manifests/rollout_ping_pong.yaml
- manifests/deployment_ping_pong.yaml
- manifests/service_ping_pong.yaml
- manifests/route_ping_pong.yaml
- manifests/service_postgres.yaml
- manifests/statefulset_postgres.yaml
- manifests/sealed_secret_postgres.yaml
- manifests/configmap_postgres.yaml
